;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Quest.Objective.Tutorial.A1",DevComment="")
+GameplayTagList=(Tag="Quest.Objective.Tutorial.A1.SelectMedic",DevComment="")
+GameplayTagList=(Tag="Quest.Objective.Tutorial.A1.CameraAdjusted",DevComment="")
+GameplayTagList=(Tag="Quest.Objective.Tutorial.A2",DevComment="")
+GameplayTagList=(Tag="Quest.Objective.Tutorial.A3",DevComment="")
+GameplayTagList=(Tag="Quest.Objective.Tutorial.A4",DevComment="")
+GameplayTagList=(Tag="Quest.Objective.Tutorial.A5",DevComment="")
+GameplayTagList=(Tag="Quest.Objective.Tutorial.A6",DevComment="")
+GameplayTagList=(Tag="Quest.Objective.Tutorial.A7",DevComment="")
+GameplayTagList=(Tag="Quest.Objective.Tutorial.A8",DevComment="")
+GameplayTagList=(Tag="Quest.Objective.Tutorial.A9",DevComment="")
+GameplayTagList=(Tag="Quest.Objective.Tutorial.B1",DevComment="")
+GameplayTagList=(Tag="Quest.Objective.Tutorial.B2",DevComment="")
+GameplayTagList=(Tag="Quest.Objective.Tutorial.B3",DevComment="")
+GameplayTagList=(Tag="Quest.Objective.Tutorial.B4",DevComment="")
+GameplayTagList=(Tag="Quest.Objective.Tutorial.B5",DevComment="")
+GameplayTagList=(Tag="Quest.Objective.Tutorial.C1",DevComment="")
+GameplayTagList=(Tag="Quest.Objective.Tutorial.C2",DevComment="")
+GameplayTagList=(Tag="Quest.Objective.Tutorial.C2.Activate",DevComment="")
+GameplayTagList=(Tag="Quest.Objective.Tutorial.C2.Move01",DevComment="")
+GameplayTagList=(Tag="Quest.Objective.Tutorial.C2.Move02",DevComment="")
+GameplayTagList=(Tag="Quest.Objective.Tutorial.C2.Attack",DevComment="")
+GameplayTagList=(Tag="Quest.Objective.Tutorial.D1",DevComment="")
+GameplayTagList=(Tag="Quest.Objective.Tutorial.D1.Overwatch01",DevComment="")
+GameplayTagList=(Tag="Quest.Objective.Tutorial.D1.Overwatch02",DevComment="")
+GameplayTagList=(Tag="Quest.Objective.Tutorial.D1.Hunker01",DevComment="")
+GameplayTagList=(Tag="Quest.Objective.Tutorial.D1.Hunker02",DevComment="")
+GameplayTagList=(Tag="Quest.Objective.Tutorial.D1.EndTurn",DevComment="")
+GameplayTagList=(Tag="Quest.Objective.Tutorial.D2",DevComment="")
+GameplayTagList=(Tag="Quest.Objective.Tutorial.D3",DevComment="")
+GameplayTagList=(Tag="Quest.Objective.Mission01.Defuse",DevComment="")
+GameplayTagList=(Tag="Quest.Objective.Mission01.Defuse.Progressed",DevComment="")
+GameplayTagList=(Tag="Quest.Objective.Mission01.Defuse.Completed",DevComment="")
+GameplayTagList=(Tag="Quest.Objective.Mission01.Evacuate",DevComment="")
+GameplayTagList=(Tag="Quest.Objective.Mission01.Evacuate.Unit",DevComment="")
+GameplayTagList=(Tag="Quest.Objective.Mission01.Evacuate.Squad",DevComment="")
